---
- name: Deploy service file
  template:
    src: "mautrix-telegram.service.j2"
    dest: "/etc/systemd/system/mautrix-telegram.service"
  notify:
    - "reload systemd"
    - "restart mautrix-telegram"
